#Reloading will not reload database stuff, a restart is required for that
mysql:
  username: 'root'
  pass: 'root'
  server: localhost
  port: 3306
  database: permissions

#mysql or h2
storage: h2

formatting:
  prefix:
    format:
      - "highest"
    #start-spacer: ""
    #middle-spacer: " "
    #end-spacer: ""
  suffix:
    format:
      - "highest"
    #start-spacer: ""
    #middle-spacer: " "
    #end-spacer: ""